### ISSUE TITLE
File 'reporters.json' not included in PyPI package

### ISSUE THREAD

**Issue by maxalbert** [approvals/ApprovalTests.Python#10]
The file `reporters.json` somehow does not seem to be included in the package available on PyPI.

To reproduce:

- Create a fresh conda environment (or virtual environment).
- `pip install approvaltests`
- Run the "getting started" example on https://github.com/approvals/ApprovalTests.Python

Traceback:

```
E
======================================================================
ERROR: test_simple (__main__.GettingStartedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_example.py", line 9, in setUp
    self.reporter = GenericDiffReporterFactory().get_first_working()
  File "/home/vagrant/miniconda/envs/debug/lib/python3.4/site-packages/approvaltests/GenericDiffReporterFactory.py", line 13, in __init__
    self.load(path)
  File "/home/vagrant/miniconda/envs/debug/lib/python3.4/site-packages/approvaltests/GenericDiffReporterFactory.py", line 36, in load
    with open(file_name, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/vagrant/miniconda/envs/debug/lib/python3.4/site-packages/approvaltests/reporters.json'

----------------------------------------------------------------------
Ran 1 test in 0.016s

FAILED (errors=1)
```

**Comment by maxalbert** [comment]
Actually, I just downloaded the tarball manually from https://pypi.python.org/packages/source/a/approvaltests/approvaltests-0.1.7.tar.gz and saw that the file `reporters.json` is included in the tarball. However, pip does not seem to install it.

**Comment by jamesrcounts** [comment]
Thanks for the report.  I updated setup.py and it should be working in 0.1.12+.

**Comment by maxalbert** [comment]
Brilliant, thanks for the quick response. I can confirm that it works now.
