### ISSUE TITLE
Missing dependency empty

### ISSUE THREAD

**Issue by objarni** [approvals/ApprovalTests.Python#100]
Get error when using latest released approvaltests.python version, guessing `empty_files` module is a new dependency not included in requirements.txt?

```...site-packages/approvaltests/utils.py", line 5, in <module>
    import empty_files
ModuleNotFoundError: No module named 'empty_files'
```

**Comment by claremacrae** [comment]
See also #102

**Comment by objarni** [comment]
To avoid this kind of issue resurfacing, maybe an automated "install and run a hello world approval test" integration test could be formulated with GitHub actions? Would love to see how such a thing could be formulated 🎉

**Comment by objarni** [comment]
As I've observed many 'smoke test issues' w.r.t ApprovalTests.Python lately, and I had a little spare time to hack around for fun, I put together a script to test whether a "hello world" test works with a specific version of the library. 

https://github.com/objarni/approvaltests-python-smoketest

**Comment by isidore** [comment]
Thank you for the suggestion @objarni ! We've added some automation to test the current release  before and after each mob to prevent this happening in the future
