### ISSUE TITLE
Beyond Compare 4

### ISSUE THREAD

**Issue by HunterMob** [approvals/ApprovalTests.Python#12]
By default Beyond Compare 4 for our installation was in Program Files, not Program Files(x86). 

Please add to reporters.json file:

    [
        "BeyondCompare4",
        "C:/Program Files/Beyond Compare 4/BCompare.exe"
    ],

**Comment by jamesrcounts** [comment]
Added... will release once I member how to do that... also once i member how to spell

**Comment by jamesrcounts** [comment]
Pushed today
