### ISSUE TITLE
trigger a `verify` via the cli

### ISSUE THREAD

**Issue by nitsanavni** [approvals/ApprovalTests.Python#127]
see working implementation here:
https://github.com/nitsanavni/katas/tree/main/approvals-cli

and some example usages here:
https://github.com/nitsanavni/katas/blob/main/approvals-cli-from-ts/test.mjs
https://github.com/nitsanavni/katas/tree/main/jq-with-approvals-cli
https://github.com/nitsanavni/katas/tree/main/jq-mars-rover

# How could it look like?
```shell
python -m approvalstests verify --test-unique-id "hello world!" --received "hello world!"
python -m approvalstests verify --test-unique-id "fizzbuzz 1-5" --received "1, 2, fizz, 4, buzz"
cat fizzbuzz | python -m approvalstests verify --test-unique-id "fizzbuzz 1-100" --received-from-stding
```
or even:
```shell
approvals -t "hello world!" -r "hello world!"
cat fizzbuzz | approvals -t "fizzbuzz 1-100" -
```

# Motivation
- Portability - this will allow us to trigger approvals from any other stack that can run child processes
- We could wrap it with a very thin SDK in the language of choice, and provide a `verify` method

# Concerns
- Speed - many such tests, I would assume would take longer to run
- How to distribute this CLI? via `pip`?

**Comment by gregorriegler** [comment]
Great Idea

I like the version with the pipe most. It would work with all sorts of inputs.
```
echo "hello" | verify -t "prints-hello"
```

**Comment by nitsanavni** [comment]
Thanks @gregorriegler !

**Comment by nitsanavni** [comment]
Added support for taking `stdin` as received, see example usage [here](https://github.com/nitsanavni/katas/tree/main/jq-with-approvals-cli)

**Comment by nitsanavni** [comment]
this was pretty much done in [this release](https://github.com/approvals/ApprovalTests.Python/releases/tag/v7.2.0)

**Comment by nitsanavni** [comment]
looks like this feature was done by @staxmanade on https://github.com/approvals/Approvals.NodeJS 8 years ago(!)
see [here](https://github.com/approvals/Approvals.NodeJS/commit/5eb19cec57a1736e8ea0a67e40223f9c4643a5f5)

and I tried it now, and it works perfectly :)
