### ISSUE TITLE
Unable to use latest approvaltests due to missing version.py

### ISSUE THREAD

**Issue by jmasonlee** [approvals/ApprovalTests.Python#134]
I am trying to import approval_utilities into my internal pypi. When I try, it fails with this error:

` 
[2023-01-26T03:11:17.957000]   FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-as484003/approvaltests/version.py'
`
This is caused by the following command failing:
`
[2023-01-26T03:11:18.020000] subprocess.CalledProcessError: Command '('/venvs/venvpython3.7/bin/pip', '--verbose', 'wheel', '-w', '/tmp/tmpasewml3n', '--no-deps', '/tmp/tmp2idqugma/approval_utilities-8.1.0.tar.gz')' returned non-zero exit status 1.`
`

We should figure out why it's missing

**Comment by nitsanavni** [comment]
what are the steps to reproduce this?

when I run this:
```bash
python -m approvaltests --test-id hello --received "hello world!"
```

I get the expected behavior.

with:

```bash
$ pip list
Package            Version
------------------ -------
approval-utilities 8.1.0
approvaltests      8.1.0
```

**Comment by jmasonlee** [comment]
To reproduce:

Download the latest approval_utilities tar.gz from https://pypi.org/project/approval-utilities/#files

untar and unzip

cd into the exctracted directory

`python3 setup.py egg_info`

**Comment by paulgale-dev** [comment]
Just wondering if there is a work around for this @jmasonlee .  It looks like our project has just encountered this issue.  Thanks

**Comment by jmasonlee** [comment]
@paulgale-dev  v8.2.1 will fix this issue for you

**Comment by jmasonlee** [comment]
@paulgale-dev if you run into issue 138 after using 8.2.1, we have a session set up to work on it tomorrow morning 7am-9am MT. Let me know if you want to join.

**Comment by paulgale-dev** [comment]
Thanks for the quick reply @jmasonlee .  Just curious if pytest-approvaltests 0.2.4 and the 8.2.1 work together.  I'll clean up my venv and try again.

**Comment by jmasonlee** [comment]
I've been using 8.2.1 directly, without the additional pytest-approvaltests package. @nitsanavni @isidore do either of you know if the pytest-approvaltests is still required?

**Comment by paulgale-dev** [comment]
@jmasonlee thanks for the follow up.  We will track, but we were able to move forward by specifying the approvaltests version in our requirements.  Still learning python dependencies 😄
