### ISSUE TITLE
Set path for approved tests in code rather than config file

### ISSUE THREAD

**Issue by nlohmann** [approvals/ApprovalTests.Python#137]
I have a test suite with over 64k tests from a single function in pytest. All approved tests are written to the same directory, which gets a bit crowded. I would like to create subdirectories to distribute the files.

Is there a way to set the directory of the approved tests in code? So far, I only found `approvaltests_config.json`, but this sets it for the whole test suite which is not sufficient for me.

**Comment by nitsanavni** [comment]
I think this can be acheived with specifying a namer, example:

https://github.com/approvals/ApprovalTests.Python/blob/71778b0049b0aa234f490bcc1652b898206d82d5/approvaltests/commandline_interface.py#L27

the `verify` call can be configured with:

```python
verify(result, , options=Options().with_namer(namer))
```

Maybe a good start is to extend [`NamerBase`](https://github.com/approvals/ApprovalTests.Python/blob/71778b0049b0aa234f490bcc1652b898206d82d5/approvaltests/namer/namer_base.py#L9)

**Comment by nlohmann** [comment]
Thanks, I made it work!

**Comment by nitsanavni** [comment]
Cool, can you share your solution?

**Comment by nlohmann** [comment]
Sure:

```py
# parameter is a string passed by pytest
# test_suite is a string passed by each test suite to create individual folders

# we want JSON output
options = approvaltests.Options({'extension_with_dot': '.json'})

# pass the parameter and set the output directory
namer = approvaltests.ScenarioNamer(approvaltests.get_default_namer(), parameter)
namer.base_namer.get_file_name()
namer.base_namer.config = {'subdirectory': os.path.join('approved_files', test_suite)}
namer.base_namer.config_loaded = True
options = options.with_namer(namer)

# json_object is built by the test and is a dict

# actual approval and passing our options
approvaltests.verify(data=json_object, encoding='utf-8', newline="\n", options=options)
```
