### ISSUE TITLE
request to support pytest configured with other naming conventions other than "test_"

### ISSUE THREAD

**Issue by emilybache** [approvals/ApprovalTests.Python#155]
Pytest has a configuration option to change the default so that instead of tests being named "test_" you can change it to "check_" or "should_" or similar. If you do that, approvals stops working. If pytest can find and execute your test I would expect approvals to also still work and evaluate whether the test passed or not.

This is the docs for pytest:

https://docs.pytest.org/en/stable/example/pythoncollection.html#change-naming-conventions

With this pytest.ini:

[pytest]
python_functions = *_check

and this test code:

def instance_check():
    result = str(Hiker().instance_answer())
    verify(result)
 
then you get an error like this:

Could not find test method/function. Possible reasons could be:
    1) approvaltests is not being used inside a test function
    2) your test framework is not supported by ApprovalTests (unittest and pytest are currently supported)."""
>           raise FrameNotFound(message)
E           approvaltests.approval_exception.FrameNotFound: Could not find test method/function. Possible reasons could be: 
E           1) approvaltests is not being used inside a test function 
E           2) your test framework is not supported by ApprovalTests (unittest and pytest are currently supported).

/usr/local/lib/python3.10/site-packages/approvaltests/core/namer.py:77: FrameNotFound

I have this cyber-dojo instance set up with this problem:

https://cyber-dojo.org/kata/edit/1cMGrz

**Comment by 4dsherwood** [comment]
@emilybache thanks!   
we are looking into this error.

I appreciate the thorough documentation that you provided. it was VERY helpful
we used the the cyber-dojo that you provided.
