### ISSUE TITLE
Update Cyber-dojo version of approval tests

### ISSUE THREAD

**Issue by 4dsherwood** [approvals/ApprovalTests.Python#156]
while we were researching the issue #155 
we noticed that cyber-dojo.org has a very old version of approval tests.

The issue presented #155 seems to be in all versions of Python Approval Tests.

**Comment by nitsanavni** [comment]
@isidore I think we can close this issue. Version of approvals seems to be up to date on cyber-dojo now.

See example - https://cyber-dojo.org/kata/edit/b0U7pS

**Comment by isidore** [comment]
done
