### ISSUE TITLE
Unnecessary and odd __name__ prefix used in file names

### ISSUE THREAD

**Issue by patkujawa-wf** [approvals/ApprovalTests.Python#2]
I finally got some output (I find it quite unusual that I got no output without creating and passing in a reporter - I thought that'd be the default), but it turns out the file name has an odd prefix (that of `__name__`). I suppose it's there for namespacing inside a package, but it prefixes `\__main__.` for my files.

![file listing](https://cloud.githubusercontent.com/assets/6391742/5115310/0b077dd6-6ffd-11e4-8af4-14e5e86af6dd.png)

The code I'm running incorporates  https://github.com/jamesrcounts/ApprovalTests.Python/commit/4038e174b14e668a44ede58fa0953d47e464fc4a and is:

```python
#! /usr/bin/env python
# Hmmm, doesn't seem to generate the 'received' file if run from the
# sheband - need to run as `python simple_verify.py` :/
import unittest
from approvaltests.Approvals import verify
from approvaltests.TestingReporter import TestingReporter


class SimpleVerifyTest(unittest.TestCase):
    def test_hello_world_string_using_verify_with_reporter(self):
        reporter = TestingReporter()
        verify("Hello World.", reporter)

if __name__ == '__main__':
    unittest.main()

```

**Comment by jamesrcounts** [comment]
Fixed by #8
