### ISSUE TITLE
Do yall have a preferred way of generating serialization for approvals?

### ISSUE THREAD

**Issue by togakangaroo** [approvals/ApprovalTests.Python#28]
I'm going nuts here trying to figure out how to serialize objects in a way that makes sense for approvals. 

* pickle is not a human readable format so it's out
* `__repr__` is worthless for objects with more than a few attributes since you have to do a whole bunch of custom stuff to make it readable on multiple lines and there seems to be no automated repr parser
* `json.dumps` works like crap, even simple things like `datetime` are not supported much less descending into object trees nor checking for cycles in a reasonable manner.
* Neither of the above supports omitting certain properties such as `last_modified` fields

What do yall use?

**Comment by patkujawa-wf** [comment]
I never quite got approvaltests working for what I wanted, but I still follow the repo and love the idea (I used the .NET lib successfully for a while), so take my input with a grain of salt. For general purpose debugging, I use a mix of repr and json: [all-purpose function for dumping any python thing in a mostly-readable manner (aka dump)](https://gist.github.com/patkujawa-wf/ae978919f4c68c9c8de8)

**Comment by tdpreece** [comment]
Hi George,

For serialising things like datetime into JSON you may want to look into
the 'default' parameter:
https://docs.python.org/3/library/json.html#json.JSONEncoder.default

Something else you may be interested in is the marshmallow package:
https://marshmallow.readthedocs.io/en/3.0/

Hope this helps.

All the best,

Tim

**Comment by emilybache** [comment]
I was thinking to close this issue since we've had some discussion a while back and no-one has suggested any concrete actions for changes in this repo. If I misunderstood the situation, please re-open.
