### ISSUE TITLE
Approval Tests with pypy

### ISSUE THREAD

**Issue by aaltat** [approvals/ApprovalTests.Python#29]
I have [pypy](https://github.com/squeaky-pl/portable-pypy#latest-python-35-release) installed and I would like to run approval tests with pypy. When I have simple example like this: 
```
import unittest

from approvaltests.approvals import verify
from approvaltests.reporters.generic_diff_reporter_factory import GenericDiffReporterFactory


class DummyTest(unittest.TestCase):

    def test_dummy(self):
        factory = GenericDiffReporterFactory()
        reporter = factory.get_first_working()
        verify('foobar', reporter)


if __name__ == "__main__":
        unittest.main()
```
And when I run it like this: `pypy3.5 dummy_test.py`, then I get error like this: 
```

mv -f /home/username/apps/pypy3.5-6.0.0-linux_x86_64-portable/lib-python/3/unittest/DummyTest.__call__.received.txt /home/username/apps/pypy3.5-6.0.0-linux_x86_64-portable/lib-python/3/unittest/DummyTest.__call__.approved.txt


E
======================================================================
ERROR: test_dummy (__main__.DummyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "utest/test/keywords/test_dummy.py", line 12, in test_dummy
    verify('foobar', reporter)
  File "/home/godtdd/apps/pypy3.5-6.0.0-linux_x86_64-portable/site-packages/approvaltests/approvals.py", line 35, in verify
    verify_with_namer(data, get_default_namer(), reporter)
  File "/home/godtdd/apps/pypy3.5-6.0.0-linux_x86_64-portable/site-packages/approvaltests/approvals.py", line 44, in verify_with_namer
    raise ApprovalException(error)
approvaltests.approval_exception.ApprovalException: 'Approval Mismatch'

----------------------------------------------------------------------
Ran 1 test in 0.057s

``` 
It looks like that in pypy the namer.py [get_base_name](https://github.com/approvals/ApprovalTests.Python/blob/master/approvaltests/core/namer.py#L27) does not work correctly and it returns something that refers to unitest framework installed in pypy. In my case it is something like this: `'/home/username/apps/pypy3.5-6.0.0-linux_x86_64-portable/lib-python/3/unittest/DummyTest.__call__'` When I run the same test with Python 2.7 or 3.6 the `get_base_name` works correctly and returns in my case this `u'/home/username/workspace/SeleniumLibrary/utest/test/keywords/approved_files/DummyTest.test_dummy'`. 

By debugging issue little further, it looks like [is_test_method](https://github.com/approvals/ApprovalTests.Python/blob/master/approvaltests/core/namer.py#L67) does not work correctly with pypy and it returns `True` also for pypy unitest frames. I was wondering could it be fixed in the [get_test_frame](https://github.com/approvals/ApprovalTests.Python/blob/master/approvaltests/core/namer.py#L59) method. It currently looks like this: 
``` 
    def get_test_frame(self, caller):
        frameNumber = 1
        for index, frame in enumerate(caller):
            if self.is_test_method(frame):
                frameNumber = index

        return frameNumber
``` 
and could it be changed like this:
```
    def get_test_frame(self, caller):
        frameNumber = 1
        for index, frame in enumerate(caller):
            if self.is_test_method(frame):
                return index
        raise AssertionError('Test frame not found.')
```
At least it fixes my problem, but my knowledge on ApprovalTests is limited and I do not know is there a good reason to loop trough all frames.

**Comment by tdpreece** [comment]
Hi,

I'm not exactly sure why this breaks for pypy but will look into.

Your suggested fix does seem like the right thing to do regardless: I don't
think there's any need to keep iterating once you find the test method.

Would you like to submit a pull request with your fix?

Thanks,

Tim

**Comment by aaltat** [comment]
I don't know pypy that deeply to know why it works differently. 

I can submit a PR to fix it. If frame is not found, should an exception be raised, like in my proposal. Or should first frame be returned, like in the original implementation?

**Comment by tdpreece** [comment]
Yes, I think raising an exception in that case would be a good idea.
Though it shouldn't be an AssertionError.  We may need a new custom
Exception if a suitable exception doesn't already exist.

Tim

**Comment by aaltat** [comment]
Any good ideas for the custom exception name?

**Comment by aaltat** [comment]
Thank you for merging the PR. I would like to use this in my project and with pypy, therefore I am asking that is there an idea when the next release would be released?
