### ISSUE TITLE
FileNotFoundError is raised config specifies non-existent sub-directory for approved files

### ISSUE THREAD

**Issue by maxalbert** [approvals/ApprovalTests.Python#37]
The [docs](https://github.com/approvals/ApprovalTests.Python/blob/master/docs/configuration.md) explain how to configure a sub-directory where the approved files will be stored.

However, currently this directory needs to be manually created. If it doesn't exist, `FileNotFoundError` is raised during the first test run. It would be good if this directory was created automatically if it doesn't exist.

**Comment by emilybache** [comment]
I just fixed this in pull request 52

**Comment by maxalbert** [comment]
Great, thanks! Also great to have the additions to the README. :)
