### ISSUE TITLE
Run CI tests on Windows

### ISSUE THREAD

**Issue by tdpreece** [approvals/ApprovalTests.Python#39]
We had an issue that only affected Windows: https://github.com/approvals/ApprovalTests.Python/issues/31

It would be good to have the travis-ci tests run on Windows too. Travis seems to support Windows to some extent (see [docs](https://docs.travis-ci.com/user/reference/windows/)) however I've not seen any examples of how to set up a Python project on Windows yet.

**Comment by claremacrae** [comment]
It might be worth looking at Appveyor, which seems to be more commonly used for Windows CI. This page may be more than you need, but looks useful: http://packaging.python.org/guides/supporting-windows-using-appveyor/

**Comment by fleimgruber** [comment]
Created #70 for this.
