### ISSUE TITLE
PyPI project description empty

### ISSUE THREAD

**Issue by objarni** [approvals/ApprovalTests.Python#46]
This page gives the impression of this project being more or less 'abandonware'.

![image](https://user-images.githubusercontent.com/68198/60389675-662df200-9ac6-11e9-846e-f98c7dee2e60.png)

**Comment by emilybache** [comment]
I will fix this as soon as I get the rights. @tdpreece can you help me with #53?

**Comment by objarni** [comment]
@emilybache any chance new features will be published to PyPI anytime soon? Was attempting to try out the new builtin/diff-tool I think is available now, but got stuck on not being able to install without doing git clone...

**Comment by emilybache** [comment]
I have to confess, I don't have the time and energy at the moment to fix this. I'm really busy.
