### ISSUE TITLE
Faulty code in GenericDiffReporter

### ISSUE THREAD

**Issue by rob-smallshire** [approvals/ApprovalTests.Python#51]
This line of code is faulty because `is_working()` is a method and it is not invoked here due to missing parentheses. The overall conditional will always evaluate to `False`.

https://github.com/approvals/ApprovalTests.Python/blob/9ef033c1517cf7fc5532ed3f41bd92973862b928/approvaltests/reporters/generic_diff_reporter.py#L44

Suggested fix:

```if not self.is_working():```

**Comment by emilybache** [comment]
I believe I have fixed this, please re-open if I misunderstood something.
