### ISSUE TITLE
requesting rights to deploy on pypi

### ISSUE THREAD

**Issue by emilybache** [approvals/ApprovalTests.Python#53]
I'd like to be able to deploy new versions of this project on pypi. At present I lack the credentials. Please could someone with the necessary credentials add me as a 'maintainer'? My username on pypi is 'emilybache'.

When I have this, I will be able to make new releases of this package.

**Comment by emilybache** [comment]
Hello @tdpreece I'd really appreciate it if you could fix this access. I just developed a new feature for supporting parameterized tests and I'd like to release a new version on pypi. Could you possibly prioritize adding me as a maintainer on pypi?

**Comment by tdpreece** [comment]
@emilybache What's your pypi username?

**Comment by emilybache** [comment]
It's the same as here - emilybache - as I wrote in my original request :-)

**Comment by tdpreece** [comment]
Missed that, sorry. You should be set up as a maintainer now. Let me know if you have any questions/problems.

**Comment by emilybache** [comment]
Thankyou!
