### ISSUE TITLE
Running approval tests under tox

### ISSUE THREAD

**Issue by abingham** [approvals/ApprovalTests.Python#56]
I've tried running some approval tests with tox, but I've received some errors. These same tests (minus the `verify()` call) work just fine under tox without approval, so my first suspicion is that approval is the culprit.

Should I expect approval to work under tox, or is that known to be problematic?

**Comment by emilybache** [comment]
I'm afraid this is not a known issue. The self-tests for this project seem to run fine with tox. Can you give more detail about your problem?

**Comment by abingham** [comment]
Things seems to be working reasonably now, so I'll go ahead and close this. Perhaps what I saw was some transient glitch in my setup.
