### ISSUE TITLE
Support for alternative namers

### ISSUE THREAD

**Issue by abingham** [approvals/ApprovalTests.Python#57]
The current "namer" system doesn't work for all scenarios. In particular, as related to #55, it can't take into account parametrized pytest tests; it produces the same name for each set of parameters.

ApprovalTests could support some system for adding (and activating) new namers that could handle special cases like that. 

Is there any will in this project for a change like that, i.e. if I wrote it and submitted a PR?

**Comment by emilybache** [comment]
I just submitted a change that should address this issue. I added a 'ScenarioNamer' class and associated unit test that demonstrates how to use it with parameterized pytest tests. Could you have a look and see if it does what you need?

**Comment by abingham** [comment]
This seems to work. Thanks!
