### ISSUE TITLE
Syntax Warning

### ISSUE THREAD

**Issue by xstrengthofonex** [approvals/ApprovalTests.Python#59]
SyntaxWarning: "is not" with a literal. Did you mean "!="? and frame[3] is not "__call__"

I'm using Python 3.8 and I started getting this warning flash up everytime I run a test. Even though it's not an error, It's not a good idea to compare strings using "is" or "is not" because it is comparison of identity not value.

**Comment by isidore** [comment]
thanks, this fixed and will be in the next release
