### ISSUE TITLE
Linux/MacOS support

### ISSUE THREAD

**Issue by dhait** [approvals/ApprovalTests.Python#6]
It appears that windows commands are hardcoded into ApprovalTests.Python.  A cross-platform version would be desirable.

**Comment by jamesrcounts** [comment]
It appears that @tdpreece already did work for linux compatibility.  What, specifically, remains to be done?  https://github.com/approvals/ApprovalTests.Python/pull/4

**Comment by isidore** [comment]
david, I have an hour or so today, got time to pair?

Llewellyn Falco
www.approvaltests.com

**Comment by dhait** [comment]
Looks like ReceivedFileLauncherReporter.get_command(..) is still returning hardcoded Windows command line.

Llewellyn -- I can't commit to a time, but if you have some changes I can try them out.

**Comment by tdpreece** [comment]
Hi David,

You can use the TextDiffReporter instead, which works with Linux and Windows.  For an example see examples/text_diff_reporter_example.py.

Tim

**Comment by dhait** [comment]
Thank you, this seems to work for me.

Today is "Giving Tuesday" -- maybe someone can give some documentation?  :-)
