### ISSUE TITLE
Is it possible to make a release?

### ISSUE THREAD

**Issue by pauline-soutrenon** [approvals/ApprovalTests.Python#66]
We'd like to use the ability to specify the encoding as contributed in the #63 
It has been a while since the last release, when do you plan to make a new release?

Thanks.

**Comment by BenEAVE** [comment]
I've just come up against this issue setting up ApprovalTests in CI for the first time. I can think of ways to work around (e.g. putting the git clone URL in the requirements for my python package) but this doesn't really scale very well, will go stale over time, can't use local package caches etc. Would be very grateful if a new release could be cut in the near future.

**Comment by tdpreece** [comment]
> We'd like to use the ability to specify the encoding as contributed in the #63
> It has been a while since the last release, when do you plan to make a new release?
> 
> Thanks.

I have just released a new version to pypi (0.2.7)

**Comment by tdpreece** [comment]
@pauline-soutrenon @BenEAVE Does the new release solve the problems you were experiencing?

**Comment by BenEAVE** [comment]
@tdpreece Yes, it does! I have now been able to set up my CI tests to run cross platform. Thank you!

Thanks in general for the library, it's such a unique and useful package.
