### ISSUE TITLE
Can we get some speed in the maintenance of this project through ensamble programming?

### ISSUE THREAD

**Issue by objarni** [approvals/ApprovalTests.Python#75]
Hello there ApprovalTests.Python maintainers and others following this repository/library!

I've noticed several PR's are kept unmerged for weeks, if not months, without a clear indication as to "why". Here are some examples:

   https://github.com/approvals/ApprovalTests.Python/pull/65     # Added 1st of March 2020. 7 months so far.
   https://github.com/approvals/ApprovalTests.Python/pull/73     # Added 29th of August 2020. 6 weeks so far.
   https://github.com/approvals/ApprovalTests.Python/pull/45     # Merged but took 1,5 months.

Any ideas to why it's like this?

Constructive idea: Why don't we set up an hour of ensemble programming and merge things / discuss how to improve the situation together? @tdpreece @emilybache @isidore 

Best regards from an almost daily user of the library,

/Olof (objarni at github)

**Comment by isidore** [comment]
I would love to do this. let's setup a time

**Comment by objarni** [comment]
Great, here's a doodle where I've set up 3 different times the next month or so that works for me. Please fill in and we'll make this happen! There is an option to login with Google, Microsoft etc accounts to that you can see if there is a collision with your calender, pretty neat.

https://doodle.com/poll/cs399v9qqvpmnpd6

**Comment by objarni** [comment]
Ok we got one answer from @emilybache what about @tdpreece and @isidore ?

**Comment by tdpreece** [comment]
Just filled in the doodle poll. Thanks for organising @objarni !

**Comment by objarni** [comment]
OK one of the slots just passed us by. @isidore do you have time to fill in the doodle?

![image](https://user-images.githubusercontent.com/68198/97004356-40d7b980-153d-11eb-93d7-f0820b405c86.png)

**Comment by objarni** [comment]
So far, no doodle slot has more than 1 maintainer, so this is not looking optimistic.

However, I'm not going to spend any more energy on this, I think I've done what I can. @isidore @tdpreece @emilybache - would you mind pinging in any other maintainer of this library that I don't know of? Or is there no interest in maintaining this library?

**Comment by tdpreece** [comment]
@objarni I'm keen to do a session on the 7th and 20th. The more maintainers the better but I think we could make progress with just the one maintainer.

**Comment by tdpreece** [comment]
@objarni and I met today to go over some of the issues. We decided that full support for Windows should be a priority so have merged a PR to run tests against Windows (as well as macOS and Ubuntu) using github actions for CI. The tests are currently failing on Windows, we could use the meeting on Nov 20th to address this.

Thanks for you time today @objarni!

**Comment by objarni** [comment]
Thank you @tdpreece nice meeting you! Cya 20th if not sooner.
