### ISSUE TITLE
Front page doc error

### ISSUE THREAD

**Issue by objarni** [approvals/ApprovalTests.Python#84]
`This example is similar to the pytest version shown above, except we are selecting the reporter in the test code rather than at runtime.`

Except we don't anymore :)

**Comment by claremacrae** [comment]
Hi Olof, how do you feel about submitting a PR?

**Comment by claremacrae** [comment]
Unless you think it needs discussion, I suppose....

**Comment by objarni** [comment]
Alrighty then - https://github.com/approvals/ApprovalTests.Python/pull/85

**Comment by obestwalter** [comment]
This can be closed, right?

**Comment by objarni** [comment]
Guess so ... thanks for ping @obestwalter
